INSERT INTO amenity (name) VALUES 
('Air conditioning'), 
('Dryer'), 
('Essentials'), 
('Heating'), 
('Hot water'), 
('Kitchen'), 
('TV'), 
('Washer'), 
('Wifi'), 
('Bathtub'), 
('Bidet'), 
('Body soap'), 
('Cleaning soap'), 
('Cleaning products'), 
('Conditioner'), 
('Hair dryer'), 
('Outdoor shower'), 
('Shampoo'), 
('Shower gel'), 
('Bed linens'), 
('Clothing storage'), 
('Drying rack for clothing'), 
('Extra pillows and blankets'), 
('Hangers'), 
('Iron'), 
('Mosquito net'), 
('Room-darkening shades'), 
('Safe'), 
('Arcade'), 
('Batting cage'), 
('Books and reading material'), 
('Bowling alley'), 
('Climbing wall'), 
('Ethernet connection'), 
('Exercise equipment'), 
('Game console'), 
('Laser tag'), 
('Life size games'), 
('Mini golf'), 
('Movie theater'), 
('Piano'), 
('Ping pong table'), 
('Pool table'), 
('Record player'), 
('Skate ramp'), 
('Sound system'), 
('Theme room'), 
('Baby bath'), 
('Baby monitor'), 
('Baby safety gates'), 
('Babysitter recommendations'), 
('Backyard'), 
('Baking sheet'), 
('Barbecue utensils'), 
('BBQ grill'), 
('Beach access'), 
('Beach essentials'), 
('Bikes'), 
('Blender'), 
('Board games'), 
('Board slip'), 
('Bread maker'), 
('Breakfast'), 
('Carbon monoxide alarm'), 
('Ceiling fan'), 
('Changing table'), 
('Children''s playroom'), 
('Children''s bikes'), 
('Children''s books and toys'), 
('Children''s dinnerware'), 
('Cleaning available during stay'), 
('Coffee'), 
('Coffee maker'), 
('Cooking basics'), 
('Crib'), 
('Dedicated workspace'), 
('Dining table'), 
('Dishes and silverware'), 
('Dishwasher')
;